KiCad/kicad-library

- README.md
I thought it'd be a good idea to mention how to download the PCB footprint libraries locally in the README here, since we point them to the repos themselves as well.
> Mention library-repos-install scripts in README

- library/conn.dcm
Add also the word 'power', otherwise you won't find the component searching on: "DC Power Jack". Which is too bad.
> Add DC Power Jack to DC Barrel Jack component

- CMakeLists.txt
The environment variable syntax used in the CMakeLists.txt can error like:
```
Make Warning (dev) at CMakeLists.txt:37 (set):
Policy CMP0053 is not set: Simplify variable reference and escape sequence
evaluation.  Run "cmake --help-policy CMP0053" for policy details.  Use the
cmake_policy command to set the policy and suppress this warning.
For input:
'$ENV{%APPDATA%}/kicad'
the old evaluation rules produce:
'/kicad'
but the new evaluation rules produce an error:
Syntax error in cmake code at
C:/Jenkins/workspace/windows-kicad-msys2-nightlies/msys64/home/SYSTEM/MINGW-packages/mingw-w64-kicad-git/src/kicad-libs/CMakeLists.txt:37
when parsing string
$ENV{%APPDATA%}/kicad
Invalid character ('%') in a variable name: ''
Using the old result for compatibility since the policy is not set.
This …
```
> Fix APPDATA environment variablt syntax for cmake

- library/device.dcm
I found misspells on the Schottly diode descrioption lines and fixed them. Glad to be pulled this request.
Thank you.
> Fixed misspells for Schottky diodes.

- library/conn.dcm
The connectors in conn.lib of the format CONN_01x02 (et al) were missing description text - I  have added this for each of these connectors.
> Added descriptions for the CONN_AAxBB connectors in conn.dcm

- library/powerint.dcm
Change "Effi cient" to "Efficient".
> Fix errant space in TNY part descriptions

- template/BeagleBone-Black-Cape/BeagleBone-Black-Cape.kicad_pcb
This change sets the grid origin to the first pin on P9.  This allows
us to easily place components with the same pin spacing and alignment.
> Align grid with BeagleBone pins

- CMakeLists.txt
Currently prefix is set to / and KICAD_DATA set to Library/Application Support/kicad This does not match the main kicad repo nor does it match any logical behaviour.
It makes more sense to remove KICAD_DATA as it can not be empty and just put the stuff in the prefix dir supplied. 
The only other sane option would be to have the prefix as /Library/Application Support with kicad_data as kicad/ but it doesn't seem much better.
This may need to be discussed or coordinated with adam prior to merge due to him having to change a line or 2 in his build scripts.
> Changed install path on osx

- library/conn.dcm
Some users expect to find the CONN_ symbols through the name "header" or "pin header."
Make sure to remove this snag from the on-boarding path to KiCad by adding that term to the description of the CONN_ components.
For example, Open Parts Library, SparkFun, Seeed, Jameco, and EAGLE all use variants of this name.
> Make the 'pin header' connectors easier to find for (new) users

- library/conn.lib
There are IDC header footprints in library already. This PR adds the filters for these footprints to pin header symbols.
> Add footprint filters for IDC headers.

- template/fp-lib-table.for-pretty
There is a missing parenthesis in the kicad lib table file which is causing import errors.
> Added missing parenthesis

- library/powerint.dcm
As noted by @diggit in issue #1006. Checking the part datasheet, TOP262 is not available in the YN package so this must have been a mistake when updating the powerint library.
> Remove TOP262YN as it's not a real part

- .gitattributes
Testing reveals that "* text=auto" provides best results. If this fixes the line-ending issues  we can push this file out to the .pretty repos too.
> Fixes for .gitattributes file

- template/fp-lib-table.for-github
- template/fp-lib-table.for-pretty
This PR adds missing .pretty repos to the lib tables:
* Battery Holders
* Housings_CSP
> Added missing library table entries

- template/fp-lib-table.for-github
- template/fp-lib-table.for-pretty
This PR adds lib-table entry for the new [Connectors_USB](https://github.com/KiCad/Connectors_USB.pretty) library
> Added lib-table entry for Connectors_USB library

- library/relays.dcm
- library/relays.lib
Added description, datasheet, and keywords. Changed reference designator
from "RL" to IEEE standard "K".
> Update OMRON Relays for KLC compliance

- library/cmos4000.dcm
Fix 'ananlog' spelling mistake in CMOS 4066; added links to datasheets for CMOS 4016, 4066
> fixed 'ananlog' in cmos 4066

- library/conn.lib
According to rule 4.12.iii, "Filters should not match the pin count."
Also, filtering for 2pol, 3pol, etc. causes the filter to miss the newly added footprints that use a [different naming convention](https://github.com/KiCad/Connectors_Terminal_Blocks.pretty/pull/11) (e. g. `TerminalBlock_Philmore_TB132_02x5mm_Straight`).
> remove number of positions from terminal block footprint filter

- library/regul.dcm
I just noticed that in `regul.dcm`, several adjustable regulators had "fixed" as a keyword, or vice-versa.  This PR corrects that.
> Several adjustable regulators had "fixed" as a keyword, or vice-versa.

- library/device.dcm
`Q_Photo_NPN_EC` had the description "Phototransistor NPN, 2-pin (C=1, E=2)".  I think it should be the other way around.
> Fix decription for Q_Photo_NPN_EC.

- library/MCU_ST_STM32.dcm
I'd change the rest of the descriptions in this manner (without checking MCU parameter correctness, as in this case). Or even further, e.g.:
Core: ARM Cortex-M4, Package: LQFP144, Flash: 256 kB, RAM: 128 kB, Frequency: 180 MHz, Voltage: 1.7..3.6V, I/O-pins: 114
Rationale: "KB" - Kelvin times something vs.  "kB" - kilobyte, "Ram" - a male sheep vs. "RAM" - Random Access Memory.
Is there any policy on this?
> MCU_ST_STM32: Correct descriptions of STM32F446Zxx

- library/wiznet.dcm
Got some time over and removed a metadata error in wiznet.lib 
(The symbol name was included in the description)
> Fixed metadata error

- library/MCU_Texas_MSP430.dcm
The MSP430G2553IPW28 is TSSOP, not TQFP.
> MCU_Texas_MSP430: fix G2553

- library/MCU_ST_STM32.dcm
I'm getting four error message when libraries are loaded when I go to select a library. I've been ignoring it for a few days but decided I'd take a look at it. There seems to be a problem in the MCU_ST_STM32.dcm library file. When I comment out four blocks I clear the error message. I'm not sure this is the correct solution, obviously it's just me having this problem so it may well be down to my configuration. The errors are:
19:45:31: Alias 'STM32L071' not found in library:
'/home/john/kicad/libs/kicad-library/library/MCU_ST_STM32.dcm'
at line 3561 offset 15
19:45:31: Alias 'STM32L071' not found in library:
'/home/john/kicad/libs/kicad-library/library/MCU_ST_STM32.dcm'
at line 3573 offset 15
19:45:31: Alias 'STM32L072' not found in library: …
> Clearing an error in STM32L071/STM32L072 loading libs

- library/MCU_Texas_MSP430.dcm
I started to clean up the MCU_Texas_MSP430 library based on the new KLC3. This PR includes updates of the description, keywords and documentation file for all parts.
Next step would be to rework the LIB file, but that does not seem to be an easy task. A lot of violations to the KLC need to be resolved, and some of the required footprints (e.g., [TVSOP](http://www.ti.com/lit/an/scba009e/scba009e.pdf)) are not available in the .pretty repositories. Any hints how to do this efficiently are welcome. Otherwise I might just update the few parts I am personally interested in.
> MCU_Texas_MSP430: update metadata

- library/MCU_Microchip_PIC12.dcm
- removed non-existent device from DCM (that device really is not produced!)
- fixed one description (package type)
> fix two minor bugs in PIC12-lib
